---

- name: Ensure packages exist
  package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python3
    - python3-pip
    - python3-kubernetes
    - python3-yaml
    - python3-jsonpatch
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
  when: ansible_os_family == 'Debian'

- name: add traefik helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"
    state: present

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: create external-services namespace
  kubernetes.core.k8s:
    name: external-services
    api_version: v1
    kind: Namespace
    state: present

- name: deploy traefik using helm
  kubernetes.core.helm:
    name: traefik-external
    chart_ref: traefik/traefik
    namespace: kube-system
    update_repo_cache: true
    values: "{{ lookup('template', 'traefik-chart-values.yaml.j2') | from_yaml }}"
    wait: yes

- name: apply traefik default headers
  kubernetes.core.k8s:
    state: present
    template: 'traefik-config.yaml.j2'

- name: apply traefik dashboard
  kubernetes.core.k8s:
    state: present
    template: 'dashboard.yaml.j2'

# ####################################################
- name: Clean up traefik tmp dir
  file:
    path: /tmp/traefik-ext/
    state: absent
