---
- name: Ensure packages exist
  package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python3
    - python3-pip
    - python3-kubernetes
    - python3-yaml
    - python3-jsonpatch
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
  when: ansible_os_family == 'Debian'

- name: add rancher helm repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"
    state: present

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: create the cattle-system namespace for rancher
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present

#deploy rancher
- name: deploy rancher with dns name {{ rancher_dns_name }}
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    namespace: cattle-system
    update_repo_cache: true
    values:
      hostname: "{{ rancher_dns_name }}"
      replicas: "{{ rancher_replicas }}"
    wait: yes
